domains:
- domain: reformer.fyi
  type: PRIMARY
name: reformer
region: sfo
services:
- github:
    branch: main
    deploy_on_push: true
    repo: ExoKomodo/reformer
  envs:
  http_port: 8080
  instance_count: 1
  instance_size_slug: basic-xxs
  name: reformer
  routes:
  - path: /
  dockerfile_path: Dockerfile
  source_dir: .
