domains:
- domain: dev.reformer.fyi
  type: PRIMARY
ingress:
  rules:
  - component:
      name: reformer
    match:
      path:
        prefix: /
name: reformer
region: sfo
services:
- dockerfile_path: Dockerfile
  github:
    branch: main
    deploy_on_push: true
    repo: ExoKomodo/reformer
  http_port: 80
  instance_count: 1
  instance_size_slug: basic-xxs
  name: reformer
  source_dir: /

