(define-module (reformer pages feed)
			   #:export (feed/index feed/post-list))

(use-modules (oop goops)
			 (sxml simple)
			 (web request)
			 (web response)
			 (web uri)
			 (reformer components navbar)
			 (reformer models)
			 (reformer html))

(define (feed/post-list posts db)
  `(div (@ (id "posts"))
		,(map
		   (lambda (post)
			 `(div
				,(xml->sxml (format #f "<p>~a</p>" (post/content post)))
				(h5 ,(format #f "~~~a" (user/handle (user/read-by-id db
																	 (post/user-id post)))))))
		   posts)))

(define (feed/index db)
  (let ((loaded-posts (post/read-all db)))
	(html-page
	  `(,((lambda () (navbar)))
		 (div (@ (style "float: left; max-width: 60vw"))
			  (h1 (a (@ (href "/feed"))
					 "Reformer Feed"))
			  ,(feed/post-list loaded-posts db))
		 (div (@ (style "float: right"))
			  (form (div (h3 "Make a post!"))
					(div (label (@ (for "handle")) "First, enter your handle...")
						 (div (input (@ (type "handle") (name "handle")))))
					(div (label (@ (for "content")) "Now, what do you want to say to the body?")
						 (div (textarea (@ (name "content")) "")))
					(button (@ (hx-post "/post")
							   (hx-swap "outerHTML")
							   (hx-target "#posts"))
							"Click me")))))))
