CREATE TABLE IF NOT EXISTS Users (id INTEGER PRIMARY KEY, handle STRING);
DELETE FROM Users;

CREATE TABLE IF NOT EXISTS Posts (id INTEGER PRIMARY KEY, content STRING, user INTEGER, FOREIGN KEY(user) REFERENCES Users(id));
DELETE FROM Posts;

