CREATE TABLE IF NOT EXISTS Users (
  id INTEGER PRIMARY KEY,
  handle TEXT NOT NULL
);
DELETE FROM Users;
CREATE TABLE IF NOT EXISTS Posts (
  id INTEGER PRIMARY KEY,
  content TEXT,
  usr INTEGER,
  FOREIGN KEY(usr) REFERENCES Users(id)
);
DELETE FROM Posts;

